# 端口号
server:
  port: 9999
  address: 0.0.0.0
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
mybatis:
  configuration:
#    开启延迟加载
    lazy-loading-enabled: true
#    关闭积极加载
    aggressive-lazy-loading: false
#    打印SQL语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    自动驼峰
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  # mybatis xml 地址
  mapperLocations: classpath:/mapper/*.xml
spring:
  # 允许bean 覆盖
  main:
    allow-bean-definition-overriding: true
  mvc:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  application:
    name: luca
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  servlet:
    multipart:
      maxRequestSize: 50MB
      maxFileSize: 50MB
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: LucaScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 30
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    #jdbc:
    #initialize-schema: never
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  SocketTimeout: 2000
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ServerListRefreshInterval: 10000
#  eureka:
#    enabled: true
#eureka:
#  instance:
#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 5
#    preferIpAddress: true
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:9998/eureka/
#    fetchRegistry: true
#    registerWithEureka: true
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver        # 配置MySQL的驱动程序类
#    url: jdbc:mysql://127.0.0.1:3306/luca?useSSL=false # 数据库连接地址
#    username: root                                  # 数据库用户名
#    password: 12345678                                # 数据库连接密码
#    dbcp2:                                          # 进行数据库连接池的配置
#      min-idle: 5                                   # 数据库连接池的最小维持连接数
#      initial-size: 5                               # 初始化提供的连接数
#      max-total: 30                                 # 最大的连接数
#      max-wait-millis: 30000                        # 等待连接获取的最大超时时间

#  r2dbc:
#    url: r2dbc:jdbc:mysql://127.0.0.1:3306/luca?useSSL=false
#    username: root
#    password: 12345678

# config 服务健康验证
health:
  config:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000