package org.ld.grpc.client;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

public interface GrpcRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:GrpcRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string params = 1;</code>
     */
    String getParams();

    /**
     * <code>string params = 1;</code>
     */
    com.google.protobuf.ByteString
    getParamsBytes();
}
