package org.ld.grpc.client;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

public interface GrpcReplyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:GrpcReply)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     */
    String getMessage();

    /**
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
    getMessageBytes();
}
