# 端口号
server:
  port: 9999
# mybatis xml 地址
mybatis:
  mapperLocations: classpath:/mapper/*.xml
spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: LucaScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 30
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
      #初始化表结构
    #jdbc:
    #initialize-schema: never


#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver        # 配置MySQL的驱动程序类
#    url: jdbc:mysql://127.0.0.1:3306/luca?useSSL=false # 数据库连接地址
#    username: root                                  # 数据库用户名
#    password: 12345678                                # 数据库连接密码
#    dbcp2:                                          # 进行数据库连接池的配置
#      min-idle: 5                                   # 数据库连接池的最小维持连接数
#      initial-size: 5                               # 初始化提供的连接数
#      max-total: 30                                 # 最大的连接数
#      max-wait-millis: 30000                        # 等待连接获取的最大超时时间